# automatically generated by generate_docs.py.
doc="""Attributes supported by this class are:
x_coord_system(type:['linear'|'log'|'category']) default="linear".
    Either 'linear', 'log' or 'category'. "Linear" and "log" makes
    x coordinate scale linearly or logarithmically. "Category"
    enumerates the X values through x_category_data and
    x_category_col attributes.
    
x_range(type:(x,y)) default=None.
    Specifies the range of X values to be displayed in the chart.
    The value can be None, in which case both the values are
    computed automatically.  Otherwise, the value must be a tuple
    of format (MIN, MAX). Both MIN and MAX must be either None or a
    number. If MIN (or MAX) is None, its value is computed
    automatically. For example, if x_range = (None,5), then the
    minimum X value is computed automatically, but the maximum X
    value is fixed at 5.
    
y_grid_style(type:line_style.T) default=gray70_dash3.
    The style of Y grid lines.
    
y_grid_over_plot(type:int) default=0.
    See x_grid_over_plot.
    
x_grid_interval(type:Number or function) default=None.
    The horizontal grid-line interval.
    
_plots(type:list) default=<function new_list at 0x8246844>.
    Used only intervally by pychart
    
x_category_data(type:list) default=None.
    Meaningful only when x_coord_system == 'category'.  This
    attribute specifies the data-set from which the X values are
    extracted. See also x_category_col.
    
y_coord_system(type:['linear'|'log'|'category']) default="linear".
    Set the Y coordinate scaling. See also x_coord_system.
    
y_category_data(type:list) default=None.
    See x_category_data.
    
y_category_col(type:int) default=1.
    See x_category_col.
    
y_range(type:(x,y)) default=None.
    Specifies the range of Y values to be displayed in the chart.
    The value can be None, in which case both the values are
    computed automatically.  Otherwise, the value must be a tuple
    of format (MIN, MAX). Both MIN and MAX must be either None or a
    number. If MIN (or MAX) is None, its value is computed
    automatically. For example, if y_range = (None,5), then the
    minimum Y value is computed automatically, but the maximum Y
    value is fixed at 5.
    
legend(type:legend.T) default:a legend is by default displayed in the right-center of the chart.    The legend of the chart.
    
size(type:(x,y)) default=(120, 110).
    The size of the chart-drawing area, excluding axis labels,
    legends, tick marks, etc.
    
loc(type:(x,y)) default=(0, 0).
    The location of the bottom-left corner of the chart.
    
y_grid_interval(type:Number or function) default=None.
    The vertical grid-line interval.
    
x_grid_over_plot(type:int) default=0.
    If true, grid lines are drawn over plots. Otherwise, plots are
    drawn over grid lines.
    
x_grid_style(type:line_style.T) default=None.
    The style of X grid lines.
    
x_axis(type:axis.X) default=None.
    The X axis. See also pychart.axis.
    
bg_style(type:fill_style.T) default=None.
    Background fill-pattern.
    
y_axis(type:axis.Y) default=None.
    The Y axis. See also pychart.axis.
    
border_line_style(type:line_style.T) default=None.
    Line style of the outer frameof the chart.
    
x_category_col(type:int) default=0.
    This attribute is meaningful only when x_coord_system ==
    'category'. This attribute selects the column of
    'x_category_data' from which X values are computed.
    
"""

