# automatically generated by generate_docs.py.
doc="""Attributes supported by this class are:
head_color(type:color.T) default=default.
    The color of the arrow head.
    
head_style(type:int) default=1.
    The value of 0 draws a triangular arrow head. 1 draws a
    swallow-tail arrow head
    
head_len(type:number) default=8.
    The length of the arrow head.
    
line_style(type:line_style.T) default=default.
    Line style.
    
thickness(type:number) default=4.
    The width of the arrow head.
    
"""

