# automatically generated by generate_docs.py.
doc="""Attributes supported by this class are:
r(type:number) default=0.0.
    The intensity of red. The value is between 0 and 1.
    
b(type:number) default=0.0.
    The intensity of blue. The value is between 0 and 1.
    
g(type:number) default=0.0.
    The intensity of green. The value is between 0 and 1.
    
"""

