# automatically generated by generate_docs.py.
doc_1="""Attributes supported by this class are:
line_style(type:line_style.T) default=default.
    See also pychart.line_style
    
tic_len(type:number) default=10.
    Length of the horizontal bars
    
"""

doc_2="""Attributes supported by this class are:
vline_style(type:line_style.T) default=None.
    The style of the vertical bar.
    
hline_style(type:line_style.T) default=default.
    The style of the horizontal bars. See also pychart.line_style.
    
tic_len(type:number) default=3.
    The length of the horizontal bars
    
"""

doc_3="""Attributes supported by this class are:
line_style(type:line_style.T) default=default.
"""

doc_4="""Attributes supported by this class are:
line_style(type:line_style.T) default=default.
box_width(type:number) default=4.
tic_len(type:number) default=4.
fill_style(type:fill_style.T) default=gray70.
"""

doc_5="""Attributes supported by this class are:
line_style(type:line_style.T) default=default.
"""

