# automatically generated by generate_docs.py.
doc="""Attributes supported by this class are:
bgcolor(type:color.T) default=white.
    The background color.
    
line_style(type:line_style.T) default=default.
    The style of the line.
    
line_interval(type:number) default=3.
    The interval between successive stitch lines.
    
"""

