# automatically generated by generate_docs.py.
doc="""Attributes supported by this class are:
right_fudge(type:number) default=5.
    Amount of space right of the legend.
    
inter_row_sep(type:number) default=0.
    Space between each entry in the legend.
    
top_fudge(type:number) default=0.
    Amount of space above the first line.
    
bottom_fudge(type:number) default=3.
    Amount of space below the last line.
    
left_fudge(type:number) default=5.
    Amount of space left of the legend.
    
shadow(type:<function ShadowType at 0x8242414>) default=None.
    The value is either None or a tuple. When non-None, a
    drop-shadow is drawn beneath the object. X-off, and y-off
    specifies the offset of the shadow relative to the object, and
    fill specifies the style of the shadow (*note fill_style::).
    
frame_fill_style(type:fill_style.T) default=white.
loc(type:(x,y)) default=None.
    Bottom-left corner of the legend.
    
frame_line_style(type:line_style.T) default=default.
"""

doc_entry="""Attributes supported by this class are:
line_len(type:number) default=10.
    Length of the sample line for line plots.
    
rect_size(type:number) default=7.
    Size of the sample 'blob' for bar range charts.
    
tick_mark(type:tick_mark.Base) default=None.
line_style(type:line_style.T) default=None.
fill_style(type:fill_style.T) default=None.
label(type:str) default="???".
"""

