# automatically generated by generate_docs.py.
doc="""Attributes supported by this class are:
y_qerror_minus_col(type:int) default=None.
    See also pychart.error_bar
    
xcol(type:int) default=0.
    The X values of sample points are extracted from "
    XCOL'th column of data. See also pychart.chart_data
    
data_label_offset(type:(x,y)) default=(0, 5).
    Location of the data label relative to the sample point.
    
data_label_format(type:printf format string) default=None.
    The format string for label printed besides each sample point.
    It can be a `printf' style format string, or a two-parameter
    function that takes the (x, y) values and returns a string. The
    appearance of the string produced here can be controlled using
    escape sequences. See also pychart.font
    
y_error_plus_col(type:int) default=None.
    The height of the errorbar is extracted from this column in
    data. Meaningful only when error_bar != None. See also
    pychart.error_bar
    
ycol(type:int) default=1.
    The X values of sample points are extracted from "
    YCOL'th column of data. See also pychart.chart_data
    
tick_mark(type:tick_mark.Base) default=None.
    Tick marks to be displayed at each sample point.
    
y_error_minus_col(type:int) default=2.
    The depth of the errorbar is extracted from this column in
    data. Meaningful only when error_bar != None. See also
    pychart.error_bar
    
line_style(type:line_style.T) default:Pick next line style from standard styles. @xref{line_style}.    The style of the line.
    
label(type:str) default="???".
    The label to be displayed in the legend. See also
    pychart.legend, See also pychart.font
    
data(type:any) default=None.
    Specifies the data points. See also pychart.chart_data
    
y_qerror_plus_col(type:int) default=None.
    See also pychart.error_bar
    
error_bar(type:error_bar.Base) default=None.
    The style of the error bar. See also pychart.error_bar
    
"""

