# automatically generated by generate_docs.py.
doc="""Attributes supported by this class are:
center(type:(x,y)) default=None.
arrow_style(type:arrow.T) default=None.
    The style of arrow that connects a label to the corresponding
    "pie".
    
start_angle(type:number) default=90.
    The angle at which the first item is drawn.
    
label_col(type:int) default=0.
    Label of items are retrieved from from this column in the
    "data" attribute
    
arc_offsets(type:list) default=None.
    You can draw each pie "slice" offset from the center of the
    circle. This attribute specifies the amount of offset (in
    points) from the center.  The value of None will draw the slice
    archored at the center.
    
label_offset(type:number) default=None.
label_line_style(type:line_style.T) default=None.
label_fill_style(type:fill_style.T) default=<fillstyle: bg=white line=default interval=3>.
data_col(type:int) default=1.
    Data values are retrieved from this column in the "data"
    attribute.
    
radius(type:number) default=None.
fill_styles(type:list) default=['black', 'gray70', 'diag', 'gray30', 'rdiag', 'gray10', 'diag2', 'white', 'rdiag2', 'vert', 'diag3', 'gray50', 'horiz', 'gray90', 'rdiag3', 'wave', 'vwave', 'stitch', 'lines'].
    The fill style of each item. The length of the list should be
    equal to the length of the data.
    
line_style(type:line_style.T) default=default.
data(type:any) default=None.
    Specifies the data points. See also pychart.chart_data
    
shadow(type:<function ShadowType at 0x8242414>) default=None.
    The value is either None or a tuple. When non-None, a
    drop-shadow is drawn beneath the object. X-off, and y-off
    specifies the offset of the shadow relative to the object, and
    fill specifies the style of the shadow (*note fill_style::).
    
"""

