# automatically generated by generate_docs.py.
doc="""Attributes supported by this class are:
xcol(type:int) default=0.
    The X values of sample points are extracted from "
    XCOL'th column of data. See also pychart.chart_data
    
max_col(type:int) default=2.
    The upper bound of the sweep is extracted from this column of
    data.
    
min_col(type:int) default=1.
    The lower bound of the sweep is extracted from this column of
    data.
    
line_style(type:line_style.T) default=default.
    The style of the boundary line.
    
fill_style(type:fill_style.T) default=<fillstyle: bg=white line=default interval=3>.
data(type:any) default=None.
    Specifies the data points. See also pychart.chart_data
    
label(type:str) default="???".
    The label to be displayed in the legend. See also
    pychart.legend, See also pychart.font
    
"""

