# automatically generated by generate_docs.py.
doc="""Attributes supported by this class are:
loc(type:tuple) default=(0, 0).
    The location of the text box.
    
left_fudge(type:number) default=5.
    The amount of space left of the box
    
arrows(type:list) default=<function new_list at 0x8246844>.
    The list of arrows. Not to be touched by the user directly
    
fill_style(type:fill_style.T) default=white.
    The fill style. See also pychart.fill_style.
    
right_fudge(type:number) default=5.
    The amount of space right of the box
    
bottom_fudge(type:number) default=5.
    The amount of space below the last line
    
radius(type:number) default=0.
    Radius of the four corners of the rectangle.  If the value is
    zero, a sharp-cornered rectangle is drawn.
    
text(type:str) default="???".
    Text body. See also pychart.font
    
top_fudge(type:number) default=0.
    The amount of space (in points) above the first line
    
line_style(type:line_style.T) default=default.
    The line style of the surrounding frame.  See also
    pychart.line_style.
    
shadow(type:<function ShadowType at 0x8242414>) default=None.
    The value is either None or a tuple. When non-None, a
    drop-shadow is drawn beneath the object. X-off, and y-off
    specifies the offset of the shadow relative to the object, and
    fill specifies the style of the shadow (*note fill_style::).
    
"""

