# automatically generated by generate_docs.py.
doc="""Attributes supported by this class are:
line_style(type:line_style.T) default=default.
    The line style of the tick mark.
    
size(type:number) default=5.
    Size of the tick mark.
    
fill_style(type:fill_style.T) default=white.
    The fill style.
    
"""

