<html>
<head>
<title>Mailing List Stats</title>
<script src="sorttable.js"></script>
<style>
body
{
    font-family: sans-serif;
}
table.sortable thead
{
    background-color:#eee;
    color:#666666;
    font-weight: bold;
    cursor: default;
}
th
{
     text-align: left;
}
h3
{
	background-color: lightblue;
}
#footer                                                                                                                                                                             
{                                                                                                                                                                                   
        font-size:80%;                                                                                                                                                              
        font-style:italic;                                                                                                                                                          
        text-align: center;                                                                                                                                                         
}
</style>
</head>
<body>
<h1>'@!heading!@' Mailing List Stats</h1>
<h3>@!author.name!@ Stats</h3>
<table>
<tr><th>Author:</th><td>@!author.mail!@</td></tr>
<tr><th>Mails:</th><td>@!author.posts!@</td></tr>
<tr><th>Threads started:</th><td>@!author.started!@</td></tr>
<tr><th>First message:</th><td>@!author.firstmsgdatestr!@</td></tr>
<tr><th>Last message:</th><td>@!author.lastmsgdatestr!@</td></tr>
<tr><th>Average mails sent per day:</th><td>@!author.average!@</td><td></tr>
</table>

<h3>Monthly Usage Charts</h3>
<ul>
<!--(for i in author.years)-->
<li><a href="ml-@!author.pagename!@-usage-@!i!@.png">@!i!@</a></li>
<!--(end)-->
</ul>
<div id="footer">Generated by MailmanStats under the Modified BSD Licence</a></div>
</body>
</html>
